version: '3.8'

services:
  # CVE Assessment API - Minimal Setup
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - APP_NAME=CVE Assessment API
      - DEBUG=false
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

# No additional services needed!
